In [1]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=';')

In [2]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [5]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [2]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [2]:
X = df.drop('quality',axis= 1)
y = df['quality']

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y,stratify=y, test_size=0.2, random_state=42)

models = {
    'Logistic_Reg': LogisticRegression(max_iter=1000),
    'random_forest':RandomForestClassifier(n_estimators = 100, random_state = 42),
    'svc': SVC(kernel = 'linear', probability = True,  random_state=42)
}
result = {}
for name, model in models.items():
    model.fit(X_train,y_train)
    pred= model.predict(X_test)
    prob=model.predict_proba(X_test) if hasattr(model, 'predict_proba') else None
    
    result[name] = {
    "Accuracy": accuracy_score(y_test,pred),
    "F1-score": f1_score(y_test, pred, average='weighted'),
    "ROC-AUC": roc_auc_score(y_test, prob, multi_class = 'ovr') if prob is not None else 'N/A',
    "Confusion Matrix" :confusion_matrix(y_test,pred)
}

for name, result_dict in result.items():
    print(f"\n==={name}===")
    for metric, value in result_dict.items():   
        print(f"{metric}: {value}")

===Logistic_Reg===
Accuracy: 0.590625
F1-score: 0.5672975809413863
ROC-AUC: 0.7648394321781414
Confusion Matrix: [[ 0  0  1  1  0  0]
 [ 0  0 10  1  0  0]
 [ 0  0 99 36  1  0]
 [ 0  0 47 78  3  0]
 [ 0  0  2 26 12  0]
 [ 0  0  0  2  1  0]]

===random_forest===
Accuracy: 0.675
F1-score: 0.6603324980581062
ROC-AUC: 0.7653235153892877
Confusion Matrix: [[  0   1   1   0   0   0]
 [  0   0   9   2   0   0]
 [  0   0 103  32   1   0]
 [  0   0  31  90   7   0]
 [  0   0   2  15  22   1]
 [  0   0   0   1   1   1]]

===svc===
Accuracy: 0.571875
F1-score: 0.5164426691729324
ROC-AUC: 0.7307818629201579
Confusion Matrix: [[  0   0   1   1   0   0]
 [  0   0  10   1   0   0]
 [  0   0 105  31   0   0]
 [  0   0  50  78   0   0]
 [  0   0   2  38   0   0]
 [  0   0   0   3   0   0]]

In [3]:
print(y_train.value_counts())
print(y_train.dtype)

quality
5    545
6    510
7    159
4     42
8     15
3      8
Name: count, dtype: int64
int64

In [21]:
y_train.value_counts(normalize= True)
y_test.value_counts(normalize= True)

quality
5    0.425000
6    0.400000
7    0.125000
4    0.034375
8    0.009375
3    0.006250
Name: proportion, dtype: float64

In [23]:
print("Train")
print(y_train.value_counts(normalize= True))
print("\nTest:")
print(y_test.value_counts(normalize= True))

Train
quality
5    0.426114
6    0.398749
7    0.124316
4    0.032838
8    0.011728
3    0.006255
Name: proportion, dtype: float64

Test:
quality
5    0.425000
6    0.400000
7    0.125000
4    0.034375
8    0.009375
3    0.006250
Name: proportion, dtype: float64

### Les hyperparamètres importants de Random Forest

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2,5,10]
}

grid_search = GridSearchCV(
    estimator = RandomForestClassifier(random_state=42),
    param_grid = param_grid,
    cv=5,
    scoring = 'f1_weighted',
    n_jobs = -1)

grid_search.fit(X_train,y_train)

print(" Best Parameters:", grid_search.best_params_)
print(" Best CV F1 score:", grid_search.best_score_)

 Best Parameters: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 100}
 Best CV F1 score: 0.660453314866549

In [13]:
model = RandomForestClassifier(n_estimators=100, max_depth=20, min_samples_split=5, 
                                 class_weight='balanced', random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

print(f1_score(y_test, pred, average='weighted'))
print(confusion_matrix(y_test, pred))

0.6546293267399949
[[  0   0   1   1   0   0]
 [  0   0   7   4   0   0]
 [  0   2 105  28   1   0]
 [  0   0  32  87   9   0]
 [  0   0   2  17  21   0]
 [  0   0   0   1   1   1]]

### appliquer SMOTE — uniquement sur X_train/y_train

In [14]:
from imblearn.over_sampling import SMOTE

print("Avant SMOTE:", y_train.value_counts())

smote = SMOTE(random_state=42, k_neighbors=2)  # k_neighbors réduit car classe 3 a très peu d'échantillons
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("\nAprès SMOTE:", y_train_smote.value_counts() if hasattr(y_train_smote, 'value_counts') else pd.Series(y_train_smote).value_counts())

Avant SMOTE: quality
5    545
6    510
7    159
4     42
8     15
3      8
Name: count, dtype: int64

Après SMOTE: quality
6    545
5    545
7    545
3    545
4    545
8    545
Name: count, dtype: int64

In [15]:
model_smote = RandomForestClassifier(n_estimators=100, max_depth=20, min_samples_split=5, random_state=42)
model_smote.fit(X_train_smote, y_train_smote)

pred_smote = model_smote.predict(X_test)

print(f1_score(y_test, pred_smote, average='weighted'))
print(confusion_matrix(y_test, pred_smote))

0.6712549603174602
[[  0   1   1   0   0   0]
 [  1   2   4   4   0   0]
 [  0   6 103  26   1   0]
 [  0   4  26  82  12   4]
 [  0   0   2  11  26   1]
 [  0   0   0   1   1   1]]

In [ ]:
# tache 2

In [12]:
df['quality_grouped'] = pd.cut(df['quality'], bins=[2, 4, 6, 8], labels=['low', 'medium', 'high'])
print(df['quality_grouped'].value_counts())

quality_grouped
medium    1319
high       217
low         63
Name: count, dtype: int64